apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mallickshop-ingress
  namespace: mallickshop
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - mallickshop.34.252.25.181.nip.io
    secretName: mallickshop-tls-secret  # Cert-Manager will manage this
  rules:
  - host: mallickshop.34.252.25.181.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mallickshop-service
            port:
              number: 80
