apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: mallickshop
spec:
  template:
    spec:
      containers:
      - name: migration
        image: arnab23/mallickshop-migration:latest
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/mallicksho"
      restartPolicy: OnFailure
