apiVersion: v1
kind: Secret
metadata:
  name: mallickshop-secrets
  namespace: mallickshop
type: Opaque
stringData:
  JWT_SECRET: "change-this-in-production"
  NEXTAUTH_SECRET: "change-this-in-production"
